name: Scenario
description: Description of scenario.
author: Caleb Bassham
version: 1.0.0
main: me.calebbassham.helpop.HelpopPlugin

commands:
  helpop:
    description: Send a message to staff.
    aliases: [ho]
  answerhelpop:
    description: Answer a helpop.
    aliases: [answer, answerho]