name: Helpop
description: System for players to send messages that can be answered by staff.
author: Caleb Bassham
version: 1.0.0
main: me.calebbassham.helpop.HelpopPlugin

commands:
  helpop:
    description: Send a message to staff.
    aliases: [ho]
  answerhelpop:
    permission: helpop.answer
    description: Answer a helpop.
    aliases: [answer, answerho]
    usage: /<command> <id> <response>
